name: "➕ Add a New Resource or Category"
description: "Suggest a new tool, library, framework, or a new category to the list."
title: "[ADD]: <resource-name>"
labels: ["enhancement", "resource-proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new resource! Please provide as much detail as possible.
  - type: input
    id: resource_name
    attributes:
      label: Resource Name
      placeholder: "e.g., HTMX, Bun, Supabase, Figma"
    validations:
      required: true
  - type: input
    id: resource_url
    attributes:
      label: Resource URL
      placeholder: "https://example.com"
    validations:
      required: true
  - type: textarea
    id: resource_details
    attributes:
      label: Resource Details
      description: "Please fill in the following sections."
      value: |
        ### Description
        (Explain what this tool does and why it is useful for builders)

        ### Category
        (Indicate which existing section it should go into)

        ### Suggestions
        (If you think a new category is needed or have other comments, write them here)
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Contribution Checklist
      options:
        - label: "I have checked that this resource is not already in the list."
          required: true
        - label: "The resource is high quality and actively maintained."
          required: true
        - label: "I am willing to submit a Pull Request if this is approved."
          required: false
