name: "🐛 Bug Report"
description: "Report a broken link, typo, or incorrect information in the list."
title: "[BUG]: <short-description>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us maintain the quality of the resources! Please describe the issue you've found.
  - type: textarea
    id: bug_details
    attributes:
      label: Bug Details
      description: "Please fill in the following sections."
      value: |
        ### Description
        (Clearly describe what is wrong. Is it a broken link? Outdated information? A typo?)

        ### Location
        (Link to the file or section where the bug is located)

        ### Suggestions / Fix
        (How should it be fixed? If it's a broken link, do you have the correct one?)
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Bug Checklist
      options:
        - label: "I have verified that the issue is still present."
          required: true
        - label: "I am willing to submit a Pull Request to fix this bug."
          required: false
